### ISSUE TITLE
安装完pjax插件后，部署时报错。

### ISSUE THREAD

**Issue by iwyang** [next-theme/pjax#2]
```
ERROR Process failed: lib/pjax/README.md
YAMLException: end of the stream or a document separator is expected at line 9, column 102:
     ... languages` and other directories:
                                         ^
    at generateError (E:\Dropbox\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (E:\Dropbox\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readDocument (E:\Dropbox\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1545:5)
    at loadDocuments (E:\Dropbox\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1588:5)
    at Object.load (E:\Dropbox\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)
    at parseYAML (E:\Dropbox\hexo\node_modules\hexo-front-matter\lib\front_matter.js:78:23)
    at parse (E:\Dropbox\hexo\node_modules\hexo-front-matter\lib\front_matter.js:54:12)
    at E:\Dropbox\hexo\node_modules\hexo\lib\plugins\processor\asset.js:33:20
    at tryCatcher (E:\Dropbox\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:544:35)
    at Promise._settlePromise (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise_array.js:145:14)
    at PromiseArray._iterate (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise_array.js:115:31)
    at PromiseArray.init [as _init] (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Dropbox\hexo\node_modules\bluebird\js\release\promise.js:673:18)
```

**Comment by stevenjoezhang** [comment]
在 Hexo 的 `_config.yml` 中找到名为 `skip_render ` 的选项，然后设置为这样
```
skip_render:
  - lib/**/*
```
